const name = ["amrit", "anurag", "nepal"];

name.forEach((value) => {
  console.log(value);
});

// arrayname.foreach((value) => {
// statement

// })

const student = ["sujata", "amrit", "sagar", "anurag", "umesh", "pragyan"];

const newstudent = student.map((newname) => {
  return newname + "amrit";
});
// return new element with array
console.log(newstudent);

const fruits = [
  "apple",
  "banana",
  "orange",
  "grape",
  "strawberry",
  "blueberry",
  "pineapple",
  "watermelon",
  "kiwi",
  "mango",
  "peach",
  "pear",
  "plum",
  "cherry",
  "apricot",
  "pomegranate",
  "fig",
  "coconut",
  "nectarine",
  "raspberry",
  "blackberry",
  "cantaloupe",
  "honeydew",
  "grapefruit",
  "lemon",
  "lime",
  "tangerine",
  "papaya",
  "passion fruit",
  "dragonfruit",
  "guava",
  "lychee",
  "persimmon",
  "starfruit",
  "aplle",
  "orange",
  "lemon",
  "lime",
  "banana",
  "mango",
  "pineapple",
  "kiwi",
  "grape",
  "strawberry",
  "blueberry",
  "raspberry",
  "blackberry",
  "apricot",
  "peach",
  "nectarine",
  "plum",
  "cherry",
  "watermelon",
  "cantaloupe",
  "honeydew",
  "pomegranate",
  "fig",
  "papaya",
  "passion fruit",
  "dragonfruit",
  "guava",
  "lychee",
  "persimmon",
  "starfruit",
  "coconut",
  "tangerine",
  "grapefruit",
  "apple",
  "orange",
  "banana",
  "grape",
  "strawberry",
  "blueberry",
  "pineapple",
  "watermelon",
  "kiwi",
  "mango",
  "peach",
  "pear",
  "plum",
  "cherry",
  "apricot",
  "pomegranate",
  "fig",
  "coconut",
  "nectarine",
  "raspberry",
  "blackberry",
  "cantaloupe",
  "honey",
];
